name: Publish Microservice
on:
  workflow_call:
    inputs:
      aws-account-id:
        description: "The aws account id used for login."
        type: string
        required: true
      aws-region:
        description: "AWS region of the codeartifact domain."
        type: string
        required: false
        default: "eu-central-1"
      organization:
        description: "Organiztaion to use."
        type: string
        required: false
        default: "kraussmaffei"
      user-name:
        description: "User name to use for commiting code changes."
        type: string
        required: false
        default: "github-actions[bot]"
      user-email:
        description: "User email to use for commiting code changes."
        type: string
        required: false
        default: "github-actions[bot]@users.noreply.github.com"
    secrets:
      user-token:
        description: "Token to be used to checkout the sources."
        required: false
      pip-index-url:
        description: "The pip index url."
        required: true
      pip-extra-index-url:
        description: "The pip extra index url."
        required: true

jobs:
  create-version-tag:
    name: "Create Version Tag"
    runs-on: ubuntu-20.04
    outputs:
      tag-version: ${{ steps.semantic-version.outputs.version_tag }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get next version
        id: semantic-version
        uses: kraussmaffei/actions/semantic-version@main
        with:
          tag_prefix: ""
          format: "${major}.${minor}.${patch}"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          short_tags: false

      - name: Push version tag
        if: github.ref == 'refs/heads/main'
        run: |
          git tag ${{ steps.semantic-version.outputs.version_tag }}
          git push origin --tags

  publish-docker-image:
    needs: [create-version-tag]
    uses: kraussmaffei/actions-docker/.github/workflows/publish.yml@main
    with:
      aws-account-id: ${{ inputs.aws-account-id }}
      aws-region: ${{ inputs.aws-region }}
      docker-file: "Dockerfile"
      docker-image-version-tag: ${{ needs.create-version-tag.outputs.tag-version }}
    secrets:
      pip-index-url: ${{ secrets.pip-index-url }}
      pip-extra-index-url: ${{ secrets.pip-extra-index-url }}

  create-pull-request:
    name: "Create pull request on balena repos"
    runs-on: ubuntu-22.04
    needs: [create-version-tag, publish-docker-image]
    strategy:
      matrix:
        repo: ["balena-smartcube", "balena-smartlink"]
    steps:
      - name: "Create pull request"
        uses: kraussmaffei/actions-microservice/create-pull-request@main
        with:
          user-token: ${{ secrets.user-token }}
          pip-index-url: ${{ secrets.pip-index-url }}
          pip-extra-index-url: ${{ secrets.pip-extra-index-url }}
          new-microservice-version: ${{ needs.create-version-tag.outputs.tag-version }}
