name: Publish Microservice
on:
  workflow_call:
    inputs:
      aws-account-id:
        description: "The aws account id used for login."
        type: string
        required: true
      aws-region:
        description: "AWS region of the codeartifact domain."
        type: string
        required: false
        default: "eu-central-1"
      organization:
        description: "Organiztaion to use."
        type: string
        required: false
        default: "kraussmaffei"
      user-name:
        description: "User name to use for commiting code changes."
        type: string
        required: false
        default: "github-actions[bot]"
      user-email:
        description: "User email to use for commiting code changes."
        type: string
        required: false
        default: "github-actions[bot]@users.noreply.github.com"
      docker-file:
        description: "The dockerfile to use for building the docker image."
        type: string
        required: false
        default: "Dockerfile"
      use-semantic-release-configuration-file:
        description: "Wheter a configuration file shall be used for semantic release or not. See, https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#configuration-file"
        type: string
        required: false
        default: "false"
    secrets:
      user-token:
        description: "Token to be used to checkout the sources."
        required: false
      pip-index-url:
        description: "The pip index url."
        required: true
      pip-extra-index-url:
        description: "The pip extra index url."
        required: true

jobs:
  semantic-release:
    name: "Run Semantic Release"
    runs-on: ubuntu-22.04
    outputs:
      release-version: ${{ steps.semantic-release.outputs.release-version }}
      new-release-created: ${{ steps.semantic-release.outputs.new-release-created }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.user-token }}

      - name: Semantic Release
        id: semantic-release
        uses: kraussmaffei/actions-microservice/create-release@main
        with:
          user-token: ${{ secrets.user-token }}
          use-configuration-file: ${{ inputs.use-semantic-release-configuration-file }}

  publish-docker-image:
    needs: [semantic-release]
    if: needs.semantic-release.outputs.new-release-created == 'true'
    uses: kraussmaffei/actions-docker/.github/workflows/publish.yml@main
    with:
      aws-account-id: ${{ inputs.aws-account-id }}
      aws-region: ${{ inputs.aws-region }}
      docker-file: ${{ inputs.docker-file }}
      docker-image-version-tag: ${{ needs.semantic-release.outputs.release-version }}
    secrets:
      pip-index-url: ${{ secrets.pip-index-url }}
      pip-extra-index-url: ${{ secrets.pip-extra-index-url }}

  create-pull-request:
    name: "Create pull request on balena repos"
    runs-on: ubuntu-22.04
    needs: [semantic-release, publish-docker-image]
    strategy:
      matrix:
        repo: ["balena-smartcube", "balena-smartlink"]
    steps:
      - name: "Create pull request"
        uses: kraussmaffei/actions-microservice/create-pull-request@main
        with:
          user-token: ${{ secrets.user-token }}
          pip-index-url: ${{ secrets.pip-index-url }}
          pip-extra-index-url: ${{ secrets.pip-extra-index-url }}
          new-microservice-version: ${{ needs.semantic-release.outputs.tag-version }}
