name: Publish Microservice
on:
  workflow_call:
    inputs:
      aws-account-id:
        description: "The aws account id used for login."
        type: string
        required: true
      aws-region:
        description: "AWS region of the codeartifact domain."
        type: string
        required: false
        default: "eu-central-1"
      organization:
        description: "Organiztaion to use."
        type: string
        required: false
        default: "kraussmaffei"
      codeartifact-repository:
        description: "The aws codeartifact repository to use."
        type: string
        required: true
      user-name:
        description: "User name to use for commiting code changes."
        type: string
        required: false
        default: "github-actions[bot]"
      user-email:
        description: "User email to use for commiting code changes."
        type: string
        required: false
        default: "github-actions[bot]@users.noreply.github.com"
    secrets:
      pip-index-url:
        description: "The pip index url."
        required: true
      pip-extra-index-url:
        description: "The pip extra index url."
        required: true
      user-token:
        description: "Token to be used to checkout the sources."
        required: false
      sonar-token:
        description: "The token to use for sonarcloud."
        required: false

jobs:
  python-quality-tasks:
    uses: kraussmaffei/actions-python/.github/workflows/quality-tasks.yml@main
    with:
      python-version: "3.8"
      python-package-path: $(echo ${GITHUB_REPOSITORY##*/} | tr -s '-' '_')
    secrets:
      pip-index-url: ${{ secrets.pip-index-url }}
      pip-extra-index-url: ${{ secrets.pip-extra-index-url }}
      user-token: ${{ secrets.user-token }}
      sonar-token: ${{ secrets.sonar-token }}

  publish-python-package:
    needs: [python-quality-tasks]
    uses: kraussmaffei/actions-python/.github/workflows/build-and-publish.yml@main
    with:
      python-version: "3.8"
      aws-account-id: ${{ inputs.aws-account-id }}
      aws-region: ${{ inputs.aws-region }}
      codeartifact-domain: ${{ inputs.organization }}
      codeartifact-repository: ${{ inputs.codeartifact-repository }}
    secrets:
      pip-index-url: ${{ secrets.pip-index-url }}
      pip-extra-index-url: ${{ secrets.pip-extra-index-url }}
      user-token: ${{ secrets.user-token }}

  publish-docker-image:
    needs: [publish-python-package]
    uses: kraussmaffei/actions-docker/.github/workflows/publish.yml@main
    with:
      aws-account-id: ${{ inputs.aws-account-id }}
      aws-region: ${{ inputs.aws-region }}
      docker-file: "Dockerfile.production"
      docker-image-version-tag: ${{ needs.publish-python-package.outputs.published-python-package-version }}
    secrets:
      pip-index-url: ${{ secrets.pip-index-url }}
      pip-extra-index-url: ${{ secrets.pip-extra-index-url }}

  create-pull-request:
    name: "Create pull request on balena repos"
    runs-on: ubuntu-22.04
    needs: [publish-docker-image, publish-python-package]
    strategy:
      matrix:
        repo: ["balena-smartcube", "balena-smartlink"]
    steps:
      - name: "Create pull request"
        uses: kraussmaffei/actions-microservice/create-pull-request@main
        with:
          user-token: ${{ secrets.user-token }}
          pip-index-url: ${{ secrets.pip-index-url }}
          pip-extra-index-url: ${{ secrets.pip-extra-index-url }}
          new-microservice-version: ${{ needs.publish-python-package.outputs.published-python-package-version }}
